# -*- coding: utf-8 -*-
"""ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCUhj9HrTmBnG0Xn09ySShggmLAfkDFP
"""

def load_sales_data(spark, file_path, file_format, schema):
    return spark.read \
        .format(file_format) \
        .schema(schema) \
        .load(file_path)

