# -*- coding: utf-8 -*-
"""transformations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i7_vtdkzB5bTiP1qx1aegeghnw-DJxjE
"""

from pyspark.sql import functions as F

def clean_and_filter_data(df):
    # Filter out null transactions and invalid amounts
    return df.filter((F.col("transaction_id").isNotNull()) & (F.col("amount") > 0))

def compute_business_metrics(df):
    # Register DataFrame as a temporary SQL View
    df.createOrReplaceTempView("sales")

    # Generate aggregated metrics via Spark SQL
    metrics_query = """
        SELECT
            product_category,
            COUNT(transaction_id) AS total_transactions,
            SUM(amount * quantity) AS total_revenue,
            AVG(amount) AS avg_transaction_value
        FROM sales
        GROUP BY product_category
        ORDER BY total_revenue DESC
    """
    return df.sparkSession.sql(metrics_query)